InventoryManagementSystem/InventoryManagementSystem/Models/Purchase.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id { get; set; }
        public string Purchase_prod { get; set; }
        public string Purchase_qnty { get; set; }
        public System.DateTime Purchase_date { get; set; }
    }
}

InventoryManagementSystem/InventoryManagementSystem/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InventoryManagementSystem.Models;

namespace InventoryManagementSystem.Controllers
{
    public class PurchaseController : Controller
    {
        private InventoryManagementSystemEntities db = new InventoryManagementSystemEntities();

        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DisplayPurchase()
        {
            List<Purchase> list = db.Purchases.OrderByDescending(x => x.id).ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult PurchaseProduct()
        {
            List<string> list = db.Products.Select(x => x.Product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View();
        }
        [HttpPost]
        public ActionResult PurchaseProduct(Purchase pur)
        {
            db.Purchases.Add(pur);
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            Purchase p = db.Purchases.Where(x => x.id == id).SingleOrDefault();
            return View(p);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Purchase p = db.Purchases.Where(x => x.id == id).SingleOrDefault();
            return View(p);
        }
        [HttpPost]
        public ActionResult Delete(int id, Purchase per)
        {
            Purchase p = db.Purchases.Where(x => x.id == id).SingleOrDefault();
            db.Purchases.Remove(p);
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            Purchase p = db.Purchases.Where(x => x.id == id).SingleOrDefault();
            List<string> list = db.Products.Select(x => x.Product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View(p);
        }
        [HttpPost]
        public ActionResult Edit(int id, Purchase pur)
        {
            Purchase p = db.Purchases.Where(x => x.id == id).SingleOrDefault();
            p.Purchase_date = pur.Purchase_date;
            p.Purchase_prod = pur.Purchase_prod;
            p.Purchase_qnty = pur.Purchase_qnty;
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }
    }
}

InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/Delete.cshtml
@model InventoryManagementSystem.Models.Purchase

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Purchased Product")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_prod)
        </dd>

        <dt>
            @Html.DisplayName("Purchased Quantity")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_qnty)
        </dd>

        <dt>
            @Html.DisplayName("Purchased Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_date)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to List", "DisplayPurchase", "Purchase", new { @class = "btn btn-success" })
        </div>
    }
</div>

InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/Detail.cshtml
@model InventoryManagementSystem.Models.Purchase

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Product Purchased")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_prod)
        </dd>

        <dt>
            @Html.DisplayName("Purchased Quantity")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_qnty)
        </dd>

        <dt>
            @Html.DisplayName("Purchased Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "PurchaseProduct", "Purchase", new { @class = "btn btn-success" })
</p>

InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/DisplayPurchase.cshtml
@model IEnumerable<InventoryManagementSystem.Models.Purchase>

@{
    ViewBag.Title = "DisplayPurchase";
}

<h2>DisplayPurchase</h2>

<p>
    @Html.ActionLink("Create New", "PurchaseProduct", "Purchase", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Purchased Product ")
        </th>
        <th>
            @Html.DisplayName("Purchased Quantity ")
        </th>
        <th>
            @Html.DisplayName("Purchased Date ")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Purchase_prod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Purchase_qnty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Purchase_date)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Purchase", new { id = item.id }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Details", "Detail", "Purchase", new { id = item.id }, new { @class = "btn btn-success" })
                @Html.ActionLink("Delete", "Delete", "Purchase", new { id = item.id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/Edit.cshtml
@model InventoryManagementSystem.Models.Purchase

@{
    ViewBag.Title = "Edit";
}

@section Scripts {
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.0.min.js"></script>
    <script type="text/javascript">

     $(document).ready(function () {
         $('input[type=datetime]').datepicker({
             dateFormat: "dd/M/yy",
             changeMonth: true,
             changeYear: true,
             yearRange: "-60:+0",
         });

     });
    </script>
}
<h2>PurchaseProduct</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Update Purchase Record</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Purchase_prod, ViewBag.ProductName as SelectList, "Select Product", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Purchase_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Product Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purchase_qnty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_qnty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Purchase Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purchase_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "DisplayPurchase", "Purchase", new { }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/PurchaseProduct.cshtml
@model InventoryManagementSystem.Models.Purchase

@{
    ViewBag.Title = "PurchaseProduct";
}
@section Scripts {
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.0.min.js"></script>
    <script type="text/javascript">

     $(document).ready(function () {
         $('input[type=datetime]').datepicker({
             dateFormat: "dd/M/yy",
             changeMonth: true,
             changeYear: true,
             yearRange: "-60:+0",
         });

     });
    </script>
}
<h2>PurchaseProduct</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Purchase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Purchase_prod, ViewBag.ProductName as SelectList, "Select Product", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Purchase_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Product Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purchase_qnty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_qnty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Purchase Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purchase_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "DisplayPurchase", "Purchase", new { }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}